module SQF.FunctionConfigSpec
    ( spec
    ) where

import           SQF.FunctionConfig
import           Test.Hspec

spec :: Spec
spec =
    it "Should render required CfgFunctions" $ do
        let res = writeModuleConfigs
                [ ModuleConfig "/path/to/Module" "Module" ["fun1", "fun2"]
                , ModuleConfig "/path/to/Module/Sub" "Module.Sub" ["fun3"]
                ]
        let expected = unlines
                [ "// This file is autogenerated by TQF - do not modify manually"
                , "class TQF_Module {"
                , "    tag = \"Module\";"
                , "    class Functions {"
                , "        file = \"/path/to/Module\""
                , "        class fun1{};"
                , "        class fun2{};"
                , "    };"
                , "};"
                , "class TQF_Module.Sub {"
                , "    tag = \"Module.Sub\";"
                , "    class Functions {"
                , "        file = \"/path/to/Module/Sub\""
                , "        class fun3{};"
                , "    };"
                , "};"
                ]
        res "" `shouldBe` expected
