on: [push]
name: test
jobs:
  runhaskell:
    name: Run unit test
    runs-on: ubuntu-latest # or macOS-latest, or windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: haskell/actions/setup@v1
      - run: stack install alex
      - run: stack install happy
      - run: stack build
      - run: stack test